### PR TITLE
Customgpiohotkey

### PR DESCRIPTION
**Pull request by Pinuct**
I made the integration of the custom gpio with the hotkey branch. I tested it with a fresh image of retropie 3.6 and a rpi3 and it works fine.

I also added the gpio customization for player 2 also.

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Thank you :)

**Comment by substring** [comment]
@digitalLumberjack just a reminder that this one has been waiting for your kind regard :)

**Comment by ian57** [comment]
Tested succesfuly on my next Pi zero  portable console with these options to allows audio, dpi tft screen ansd control on the GPIO. Only 2 pins remains free ;)
```
#options mk_arcade_joystick_rpi map=1,2
# gpio with button order: Y-,Y+,X-,X+,start,select,a,b,tr,y,x,tl
options mk_arcade_joystick_rpi map=5 gpio=2,3,4,14,15,25,5,6,12,19,16,26
```

**Comment by digitalLumberjack** [comment]
Thanks dude

**Comment by digitalLumberjack** [comment]
We will test that in recalbox 4.1

**Pull request merged**
